# Run settings
mode: train  # train or eval
render: false
record: false
checkpoint: null  # path to checkpoint for evaluation
scenario: 'austria.yml'  # Scenario file name

# Model settings
model_type: ppo  # dqn or ppo
use_camera: false  # Enable or disable the use of RGB camera
frame_skip: 4  # Skip frames for faster stepping when using camera

# General Hyperparameters
gamma: 0.99
hidden_size: 128
episodes: 10000
train_freq: 10
min_samples: 2000
batch_size: 256
short_episode_threshold: 100
max_short_episodes: 5

# DQN-specific parameters
learning_rate: 0.001
epsilon_start: 1.0
epsilon_end: 0.001
epsilon_decay: 0.999
buffer_size: 100000
target_update_freq: 10

# PPO-specific parameters
actor_lr: 0.0003
critic_lr: 0.001
ppo_epochs: 5
clip_param: 0.15
gae_lambda: 0.95
min_std: 1e-6